//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34011
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Gameplay.Core.Type;


namespace Gameplay.Core.Gamestates 
{
	public class MultiplayerState : IGameState
	{
		public MultiplayerState()
		{

		}


		#region IGameState implementation
		public string GetName ()
		{
			return "Multiplayer State";
		}
		public GamestateType GetGamestateType ()
		{
			return GamestateType.Multiplayer;
		}
		public void Enter ()
		{
		}
		public void Leave()
		{

		}
		public void Reset()
		{

		}
		#endregion
	}
}

