//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34011
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Assets.Scripts.Gameplay.Core.Type
{
    /// <summary>
    /// All types of gamestates
    /// </summary>
	public enum GamestateType
	{
        Invalid,        // If none is set
		MainMenu,
		Training,
		Multiplayer
	}
}

